FILESEXTRAPATHS:prepend := "${THISDIR}/files/6.6/:"

SRC_URI += "file://0001-mac80211-mlme-s1g-ecsa-support.patch"
SRC_URI += "file://0002-mac80211-tx-s1g-AP-ecsa-support.patch"
SRC_URI += "file://0003-mac80211-IBSS-bridge-support.patch"
SRC_URI += "file://0004-mac80211-Mesh-support.patch"
SRC_URI += "file://0005-mmc-sdio-1.8v-support-quirk.patch"
SRC_URI += "file://0006-spi-Force-CS_HIGH-if-GPIO-descriptors-are-used.patch"
SRC_URI += "file://0007-spi-support-control-of-SPI-CS-pin-on-initialisation.patch"
SRC_URI += "file://0008-mac80211-implement-support-for-thin-LMAC-S1G-NDP-blo.patch"
SRC_URI += "file://0009-kernel-enable-dev-coredump-by-default.patch"
SRC_URI += "file://0010-mac80211-introduce-modparam-to-configure-association.patch"
SRC_URI += "file://0011-wifi-mac80211-Initialize-EWMA-fail-avg-to-1.patch"
SRC_URI += "file://0012-wifi-nl80211-Introduce-the-channel-flag-IEEE80211_CH.patch"
SRC_URI += "file://0013-Revert-Revert-pinctrl-bcm2835-Set-base-to-0-give-exp.patch"
SRC_URI += "file://0014-mac80211-add-halow-specific-mesh-optimizations.patch"
SRC_URI += "file://0015-imx6ul-var-dart-add-support-for-SPI-attached-Morse-M.patch"
SRC_URI += "file://0016-Revert-LF-8808-spi-imx-fix-message-endian-convert-in.patch"
SRC_URI += "file://0017-Revert-LF-6680-spi-imx-add-dma-support-for-target-mo.patch"
SRC_URI += "file://0018-LF-15429-spi-imx-add-dynamic-burst-for-spi-sdma-mode.patch"
SRC_URI += "file://0019-spi-imx-restore-gfp-parameter-following-NXP-changes.patch"
SRC_URI += "file://0020-spi-imx-force-use_dynamic_burst-true.patch"

SRC_URI += "file://spi_imx_module.cfg"